// 修改 js/ 后构建；--check 仅检查源文件、缓存版本和产物是否一致。
import { readFileSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
const read = path => readFileSync(new URL(path, import.meta.url), 'utf8');
const hash = text => createHash('sha256').update(text).digest('hex').slice(0, 12);
const modules = ['config', 'track', 'music', 'noise', 'shake', 'sky', 'sun', 'mountains', 'snow', 'postprocess', 'main'];
const sections = modules.map(name => {
  const source = read(`./js/${name}.js`).replace(/^import\s+.*?;\s*$/gm, '').replace(/^export\s+(?=(const|function|class)\b)/gm, '');
  return `\n// Source: js/${name}.js\n${source}`;
});
const bundle = `// Generated by build.mjs from js/; edit the source modules.\n(function () {\n'use strict';\n${sections.join('\n')}\n})();\n`;
const page = read('./index.html').replace(/src="bundle\.js(?:\?v=[^"]+)?"/, `src="bundle.js?v=${hash(bundle)}"`).replace(/href="css\/style\.css(?:\?v=[^"]+)?"/, `href="css/style.css?v=${hash(read('./css/style.css'))}"`);
for (const [path, value] of [['./bundle.js', bundle], ['./index.html', page]]) {
  if (process.argv.includes('--check')) {
    if (read(path) !== value) throw new Error(`请运行群山 build.mjs 同步 ${path}`);
  } else writeFileSync(new URL(path, import.meta.url), value);
}
console.log(process.argv.includes('--check') ? '群山源码和产物已同步。' : '已生成群山入口与带版本的脚本。');
