export const songs = [
  { title: '千千阙歌 — 陈慧娴', file: 'qianqianquege.mp3' },
  { title: '我只在乎你 — 邓丽君', file: 'wozhizaihuni.mp3' },
  { title: 'Bubblegum Trash — Starjunk 95', file: 'bubblegum-trash-starjunk-95.mp3' },
  { title: 'Error 4 On The Floor — Starjunk 95', file: 'error-4-on-the-floor-starjunk-95.mp3' },
  { title: 'Magic (feat. Mylk) — Moe Shop', file: 'magic-moe-shop-feat-mylk.mp3' },
  { title: 'Stardust Circuit — Starjunk 95', file: 'stardust-circuit-starjunk-95.mp3' },
  { title: 'State Your Name — Starjunk 95', file: 'state-your-name-starjunk-95.mp3' },
  { title: '圣诞星 (feat. 杨瑞代) — 周杰伦', file: 'shengdanxing-jay-chou.mp3' },
  { title: '爱的飞行日记 (feat. 杨瑞代) — 周杰伦', file: 'aidefeixingriji-jay-chou.mp3' },
  { title: '等你下课 (with 杨瑞代) — 周杰伦', file: 'dengnixiake-jay-chou.mp3' },
  { title: '莫再提 — 徐良', file: 'mozaiti-xu-liang.mp3' },
  { title: '被风吹过的夏天 (Live) — 林俊杰', file: 'beifengchuiguodexiatian-live-lin-junjie.mp3' },
  { title: 'I Am Fine — Yanzi Sun', file: 'i-am-fine-yanzi-sun.mp3' },
  { title: '留不住的夏天 (伴奏) — 黃霄雲', file: 'liu-bu-zhu-de-xia-tian-instrumental-huang-xiaoyun.mp3' },
  { title: 'I Want To Become an Immortal — Liu Huan', file: 'i-want-to-become-an-immortal-liu-huan.mp3' },
  { title: 'Star Lighting — Zhihua Zheng', file: 'star-lighting-zhihua-zheng.mp3' },
  { title: 'Step Aside — Rene Liu', file: 'step-aside-rene-liu.mp3' },
  { title: 'Time and Time Again — Liu Huan', file: 'time-and-time-again-liu-huan.mp3' },
  { title: '一千個傷心的理由 (國) — Jacky Cheung', file: 'yi-qian-ge-shang-xin-de-li-you-jacky-cheung.mp3' },
  { title: '一場遊戲一場夢 — Dave Wang', file: 'yi-chang-you-xi-yi-chang-meng-dave-wang.mp3' },
  { title: '凤凰于飞 — Liu Huan', file: 'feng-huang-yu-fei-liu-huan.mp3' },
  { title: '匿名的好友 — Rainie Yang', file: 'ni-ming-de-hao-you-rainie-yang.mp3' },
  { title: '寂寞不痛 — A-Lin', file: 'ji-mo-bu-tong-a-lin.mp3' },
  { title: '弯弯的月亮 — Liu Huan', file: 'wan-wan-de-yue-liang-liu-huan.mp3' },
  { title: '愛我別走 — A-Yue Chang', file: 'ai-wo-bie-zou-a-yue-chang.mp3' },
  { title: '成全 (Live) — Yoga Lin', file: 'cheng-quan-live-yoga-lin.mp3' },
  { title: '是否我真的一無所有 — Dave Wang', file: 'shi-fou-wo-zhen-de-yi-wu-suo-you-dave-wang.mp3' },
  { title: '爱笑的眼睛 — Ren Xuechen', file: 'ai-xiao-de-yan-jing-ren-xuechen.mp3' },
  { title: '獨角戲 — Valen Hsu', file: 'du-jiao-xi-valen-hsu.mp3' },
  { title: '留不住的夏天 — 黃霄雲', file: 'liu-bu-zhu-de-xia-tian-huang-xiaoyun.mp3' },
];
