export const songs = [
  { title: '千千阙歌 — 陈慧娴', file: 'qianqianquege.mp3' },
  { title: '我只在乎你 — 邓丽君', file: 'wozhizaihuni.mp3' },
  { title: 'Bubblegum Trash — Starjunk 95', file: 'bubblegum-trash-starjunk-95.mp3' },
  { title: 'Error 4 On The Floor — Starjunk 95', file: 'error-4-on-the-floor-starjunk-95.mp3' },
  { title: 'Magic (feat. Mylk) — Moe Shop', file: 'magic-moe-shop-feat-mylk.mp3' },
  { title: 'Stardust Circuit — Starjunk 95', file: 'stardust-circuit-starjunk-95.mp3' },
  { title: 'State Your Name — Starjunk 95', file: 'state-your-name-starjunk-95.mp3' },
  { title: '圣诞星 — 周杰伦、杨瑞代', file: 'shengdanxing-jay-chou.mp3' },
  { title: '爱的飞行日记 — 周杰伦、杨瑞代', file: 'aidefeixingriji-jay-chou.mp3' },
  { title: '等你下课 — 周杰伦、杨瑞代', file: 'dengnixiake-jay-chou.mp3' },
  { title: '莫再提 — 徐良', file: 'mozaiti-xu-liang.mp3' },
  { title: '被风吹过的夏天（现场版） — 林俊杰', file: 'beifengchuiguodexiatian-live-lin-junjie.mp3' },
  { title: '我不难过 — 孙燕姿', file: 'i-am-fine-yanzi-sun.mp3' },
  { title: '留不住的夏天（伴奏） — 黄霄云', file: 'liu-bu-zhu-de-xia-tian-instrumental-huang-xiaoyun.mp3' },
  { title: '我欲成仙 — 刘欢', file: 'i-want-to-become-an-immortal-liu-huan.mp3' },
  { title: '星星点灯 — 郑智化', file: 'star-lighting-zhihua-zheng.mp3' },
  { title: '成全 — 刘若英', file: 'step-aside-rene-liu.mp3' },
  { title: '千万次的问 — 刘欢', file: 'time-and-time-again-liu-huan.mp3' },
  { title: '一千个伤心的理由（国语版） — 张学友', file: 'yi-qian-ge-shang-xin-de-li-you-jacky-cheung.mp3' },
  { title: '一场游戏一场梦 — 王杰', file: 'yi-chang-you-xi-yi-chang-meng-dave-wang.mp3' },
  { title: '凤凰于飞 — 刘欢', file: 'feng-huang-yu-fei-liu-huan.mp3' },
  { title: '匿名的好友 — 杨丞琳', file: 'ni-ming-de-hao-you-rainie-yang.mp3' },
  { title: '寂寞不痛 — 黄丽玲', file: 'ji-mo-bu-tong-a-lin.mp3' },
  { title: '弯弯的月亮 — 刘欢', file: 'wan-wan-de-yue-liang-liu-huan.mp3' },
  { title: '爱我别走 — 张震岳', file: 'ai-wo-bie-zou-a-yue-chang.mp3' },
  { title: '成全（现场版） — 林宥嘉', file: 'cheng-quan-live-yoga-lin.mp3' },
  { title: '是否我真的一无所有 — 王杰', file: 'shi-fou-wo-zhen-de-yi-wu-suo-you-dave-wang.mp3' },
  { title: '爱笑的眼睛 — 任雪晨', file: 'ai-xiao-de-yan-jing-ren-xuechen.mp3' },
  { title: '独角戏 — 许茹芸', file: 'du-jiao-xi-valen-hsu.mp3' },
  { title: '留不住的夏天 — 黄霄云', file: 'liu-bu-zhu-de-xia-tian-huang-xiaoyun.mp3' },
  { title: '风继续吹（2026年重制版） — 张国荣', file: 'feng-ji-xu-chui-remastered-2026-leslie-cheung.mp3' },
  { title: '小幸运 — 文慧如', file: 'a-little-happiness-boon-hui-lu.mp3' },
  { title: '小幸运（电影《我的少女时代》主题曲） — 田馥甄', file: 'a-little-happiness-from-our-times-hebe-tien.mp3' },
  { title: '童话 — 光良', file: 'fairy-tale-michael-wong.mp3' },
  { title: '童话镇 — 周二珂', file: 'fairytale-town-chloe-er.mp3' },
  { title: '空心（现场版） — 黄霄云、刘端端', file: 'hollow-live-huang-xiaoyun-duanduan-liu.mp3' },
  { title: '离开我的依赖（现场版） — 王赫野、黄霄云', file: 'li-kai-wo-de-yi-lai-live-wang-heye-huang-xiaoyun.mp3' },
  { title: '不再犹豫 — Beyond', file: 'bu-zai-you-yu-beyond.mp3' },
  { title: '空心 — 光泽', file: 'kong-xin-guang-ze.mp3' },
  { title: '董小姐 — 宋冬野', file: 'dong-xiao-jie-song-dongye.mp3' },
  { title: '依恋 — 蔡淳佳', file: 'yi-lian-cai-chun-jia.mp3' },
  { title: '不想失去你 — 张雨生', file: 'bu-xiang-shi-qu-ni-zhang-yu-sheng.mp3' },
  { title: '再见只是陌生人 — 庄心妍', file: 'zai-jian-zhi-shi-mo-sheng-ren-zhuang-xin-yan.mp3' },
  { title: '生如夏花 — 朴树', file: 'sheng-ru-xia-hua-pu-shu.mp3' },
  { title: 'Monody (feat. Laura Brehm) — TheFatRat', file: 'monody-thefatrat-laura-brehm.mp3' },
  { title: '一万个舍不得 — 庄心妍', file: 'yi-wan-ge-she-bu-de-zhuang-xin-yan.mp3' },
  { title: '但愿人长久 — 王菲', file: 'dan-yuan-ren-chang-jiu-wang-fei.mp3' },
  { title: '很爱很爱你 — 刘若英', file: 'hen-ai-hen-ai-ni-liu-ruo-ying.mp3' },
  { title: '星辰大海 — 黄霄云', file: 'xing-chen-da-hai-huang-xiao-yun.mp3' },
  { title: '橄榄树 — 齐豫', file: 'gan-lan-shu-qi-yu.mp3' },
  { title: '江南 — 林俊杰', file: 'jiang-nan-lin-jun-jie.mp3' },
  { title: '烟火里的尘埃 — 黄霄云', file: 'yan-huo-li-de-chen-ai-huang-xiao-yun.mp3' },
  { title: '白桦林 — 朴树', file: 'bai-hua-lin-pu-shu.mp3' },
  { title: '稻香 — 周杰伦', file: 'dao-xiang-zhou-jie-lun.mp3' },
  { title: '花心 — 周华健', file: 'hua-xin-zhou-hua-jian.mp3' },
  { title: 'Ladies’Night — 刘舒妤', file: 'ladies-night-liu-shu-yu.mp3' },
  { title: 'Soul Below — LJones', file: 'soul-below-ljones.mp3' },
  { title: 'Tak Sama — 刘舒妤', file: 'tak-sama-liu-shu-yu.mp3' },
  { title: '你知道这不是爱 — 蔡诗芸', file: 'ni-zhi-dao-zhe-bu-shi-ai-cai-shi-yun.mp3' },
  { title: '最初的记忆 — ycccc', file: 'zui-chu-de-ji-yi-ycccc.mp3' },
  { title: '最好的安排 — 刘舒妤', file: 'zui-hao-de-an-pai-liu-shu-yu.mp3' },
  { title: '她比我懂你吗 — 金海心', file: 'ta-bi-wo-dong-ni-ma-jin-hai-xin.mp3' },
  { title: '对岸 — 金海心', file: 'dui-an-jin-hai-xin.mp3' },
  { title: '想象爱 — 蔡诗芸', file: 'xiang-xiang-ai-cai-shi-yun.mp3' },
  { title: '是我不够好 — 李毓芬', file: 'shi-wo-bu-gou-hao-li-yu-fen.mp3' },
  { title: '比天空还远的季节 — 金海心', file: 'bi-tian-kong-hai-yuan-de-ji-jie-jin-hai-xin.mp3' },
  { title: '海海海 — 阿悄', file: 'hai-hai-hai-a-qiao.mp3' },
  { title: '爱你 — 徐俊雅', file: 'ai-ni-xu-jun-ya.mp3' },
  { title: '爱我不要丢下我 — 王思思', file: 'ai-wo-bu-yao-diu-xia-wo-wang-si-si.mp3' },
  { title: '特别的人 — 方大同', file: 'te-bie-de-ren-fang-da-tong.mp3' },
  { title: '白色羽毛 — 芮恩', file: 'bai-se-yu-mao-rui-en.mp3' },
  { title: '罗生门（Follow） — 梨冻紧、张子豪', file: 'luo-sheng-men-li-dong-jin-zhang-zi-hao.mp3' },
  { title: '迷人的危险 — dance flow', file: 'mi-ren-de-wei-xian-dance-flow.mp3' },
  { title: '那么骄傲（重遇版） — 金海心', file: 'na-me-jiao-ao-chong-yu-jin-hai-xin.mp3' },
  { title: '父亲 — 筷子兄弟', file: 'fu-qin-kuai-zi-xiong-di.mp3' },
  { title: '打火机 — 曾千倚', file: 'da-huo-ji-zeng-qian-yi.mp3' },
  { title: '老男孩 — 筷子兄弟', file: 'lao-nan-hai-kuai-zi-xiong-di.mp3' },
  { title: '一千年以后 — 林俊杰', file: 'yi-qian-nian-yi-hou-lin-jun-jie.mp3' },
  { title: '你啊你啊 — 魏如萱', file: 'ni-a-ni-a-wei-ru-xuan.mp3' },
  { title: '你在看孤独的风景 — 本兮、单小源', file: 'ni-zai-kan-gu-du-de-feng-jing-ben-xi-shan-xiao-yuan.mp3' },
  { title: '你的承诺（国语版） — 海鸣威', file: 'ni-de-cheng-nuo-guo-yu-hai-ming-wei.mp3' },
  { title: '原谅我一次 — 岁月无痕', file: 'yuan-liang-wo-yi-ci-sui-yue-wu-hen.mp3' },
  { title: '埋葬冬天 — 汪苏泷、阿悄', file: 'mai-zang-dong-tian-wang-su-long-a-qiao.mp3' },
  { title: '怎么办我想你 — 本兮', file: 'zen-me-ban-wo-xiang-ni-ben-xi.mp3' },
  { title: '我爱你 — 卢广仲', file: 'wo-ai-ni-lu-guang-zhong.mp3' },
  { title: '我爱你 — 王菲', file: 'wo-ai-ni-wang-fei.mp3' },
  { title: '我爱你 — 程佳佳', file: 'wo-ai-ni-cheng-jia-jia.mp3' },
  { title: '我的回忆不是我的 — 泳儿、海鸣威', file: 'wo-de-hui-yi-bu-shi-wo-de-yong-er-hai-ming-wei.mp3' },
  { title: '放弃 — 星弟', file: 'fang-qi-xing-di.mp3' },
  { title: '无限速 — 本兮、阿悄', file: 'wu-xian-su-ben-xi-a-qiao.mp3' },
  { title: '老人与海 — 海鸣威', file: 'lao-ren-yu-hai-hai-ming-wei.mp3' },
  { title: '老男孩 — 雷婷', file: 'lao-nan-hai-lei-ting.mp3' },
  { title: '至少还有你 — 林忆莲', file: 'zhi-shao-hai-you-ni-lin-yi-lian.mp3' },
  { title: '落差 — In K、王忻辰', file: 'luo-cha-in-k-wang-xin-chen.mp3' },
  { title: '错错错 — 六哲、陈娟儿', file: 'cuo-cuo-cuo-liu-zhe-chen-juan-er.mp3' },
  { title: '身骑白马 — 徐佳莹', file: 'shen-qi-bai-ma-xu-jia-ying.mp3' },
  { title: 'River Flows in You — Martin Ermen', file: 'river-flows-in-you-martin-ermen.mp3' },
  { title: 'Secret of my heart — Mai Kuraki', file: 'secret-of-my-heart-mai-kuraki.mp3' },
  { title: 'Since U Been Gone — Kelly Clarkson', file: 'since-u-been-gone-kelly-clarkson.mp3' },
  { title: 'Sunflower (Spider-Man: Into the Spider-Verse) — Post Malone, Swae Lee', file: 'sunflower-post-malone-swae-lee.mp3' },
  { title: 'Time after time ~花舞う街で~ (theater version) — Mai Kuraki', file: 'time-after-time-theater-version-mai-kuraki.mp3' },
  { title: 'Where Did U Go — 邓紫棋', file: 'where-did-u-go-gem.mp3' },
  { title: 'Your Best Friend — Mai Kuraki', file: 'your-best-friend-mai-kuraki.mp3' },
  { title: 'Your Song — 张靓颖', file: 'your-song-zhang-liang-ying.mp3' },
  { title: '一千个伤心的理由 — 张学友', file: 'yi-qian-ge-shang-xin-de-li-you-zhang-xue-you-aplmate.mp3' },
  { title: '三角题 — 周二珂', file: 'san-jiao-ti-zhou-er-ke.mp3' },
  { title: '刀马旦 — 李玟', file: 'dao-ma-dan-li-wen.mp3' },
  { title: '创作者（《反恐行动之浪漫满屋》微电影主题曲）— 本兮、徐良', file: 'chuang-zuo-zhe-ben-xi-xu-liang.mp3' },
  { title: '勇敢 — BY2', file: 'yong-gan-by2.mp3' },
  { title: '我知道 — BY2', file: 'wo-zhi-dao-by2.mp3' },
  { title: '燕归巢 — 许嵩', file: 'yan-gui-chao-xu-song.mp3' },
  { title: '萤火虫 — 林依晨', file: 'ying-huo-chong-lin-yi-chen.mp3' },
];
