export const songs = [
  { title: '千千阙歌 — 陈慧娴', file: 'qianqianquege.mp3' },
  { title: '我只在乎你 — 邓丽君', file: 'wozhizaihuni.mp3' },
  { title: 'Bubblegum Trash — Starjunk 95', file: 'bubblegum-trash-starjunk-95.mp3' },
  { title: 'Error 4 On The Floor — Starjunk 95', file: 'error-4-on-the-floor-starjunk-95.mp3' },
  { title: 'Magic (feat. Mylk) — Moe Shop', file: 'magic-moe-shop-feat-mylk.mp3' },
  { title: 'Stardust Circuit — Starjunk 95', file: 'stardust-circuit-starjunk-95.mp3' },
  { title: 'State Your Name — Starjunk 95', file: 'state-your-name-starjunk-95.mp3' },
  { title: '圣诞星 — 周杰伦、杨瑞代', file: 'shengdanxing-jay-chou.mp3' },
  { title: '爱的飞行日记 — 周杰伦、杨瑞代', file: 'aidefeixingriji-jay-chou.mp3' },
  { title: '等你下课 — 周杰伦、杨瑞代', file: 'dengnixiake-jay-chou.mp3' },
  { title: '莫再提 — 徐良', file: 'mozaiti-xu-liang.mp3' },
  { title: '被风吹过的夏天（现场版） — 林俊杰', file: 'beifengchuiguodexiatian-live-lin-junjie.mp3' },
  { title: '我不难过 — 孙燕姿', file: 'i-am-fine-yanzi-sun.mp3' },
  { title: '留不住的夏天（伴奏） — 黄霄云', file: 'liu-bu-zhu-de-xia-tian-instrumental-huang-xiaoyun.mp3' },
  { title: '我欲成仙 — 刘欢', file: 'i-want-to-become-an-immortal-liu-huan.mp3' },
  { title: '星星点灯 — 郑智化', file: 'star-lighting-zhihua-zheng.mp3' },
  { title: '成全 — 刘若英', file: 'step-aside-rene-liu.mp3' },
  { title: '千万次的问 — 刘欢', file: 'time-and-time-again-liu-huan.mp3' },
  { title: '一千个伤心的理由（国语版） — 张学友', file: 'yi-qian-ge-shang-xin-de-li-you-jacky-cheung.mp3' },
  { title: '一场游戏一场梦 — 王杰', file: 'yi-chang-you-xi-yi-chang-meng-dave-wang.mp3' },
  { title: '凤凰于飞 — 刘欢', file: 'feng-huang-yu-fei-liu-huan.mp3' },
  { title: '匿名的好友 — 杨丞琳', file: 'ni-ming-de-hao-you-rainie-yang.mp3' },
  { title: '寂寞不痛 — 黄丽玲', file: 'ji-mo-bu-tong-a-lin.mp3' },
  { title: '弯弯的月亮 — 刘欢', file: 'wan-wan-de-yue-liang-liu-huan.mp3' },
  { title: '爱我别走 — 张震岳', file: 'ai-wo-bie-zou-a-yue-chang.mp3' },
  { title: '成全（现场版） — 林宥嘉', file: 'cheng-quan-live-yoga-lin.mp3' },
  { title: '是否我真的一无所有 — 王杰', file: 'shi-fou-wo-zhen-de-yi-wu-suo-you-dave-wang.mp3' },
  { title: '爱笑的眼睛 — 任雪晨', file: 'ai-xiao-de-yan-jing-ren-xuechen.mp3' },
  { title: '独角戏 — 许茹芸', file: 'du-jiao-xi-valen-hsu.mp3' },
  { title: '留不住的夏天 — 黄霄云', file: 'liu-bu-zhu-de-xia-tian-huang-xiaoyun.mp3' },
  { title: '风继续吹（2026年重制版） — 张国荣', file: 'feng-ji-xu-chui-remastered-2026-leslie-cheung.mp3' },
  { title: '小幸运 — 文慧如', file: 'a-little-happiness-boon-hui-lu.mp3' },
  { title: '小幸运（电影《我的少女时代》主题曲） — 田馥甄', file: 'a-little-happiness-from-our-times-hebe-tien.mp3' },
  { title: '童话 — 光良', file: 'fairy-tale-michael-wong.mp3' },
  { title: '童话镇 — 周二珂', file: 'fairytale-town-chloe-er.mp3' },
  { title: '空心（现场版） — 黄霄云、刘端端', file: 'hollow-live-huang-xiaoyun-duanduan-liu.mp3' },
  { title: '离开我的依赖（现场版） — 王赫野、黄霄云', file: 'li-kai-wo-de-yi-lai-live-wang-heye-huang-xiaoyun.mp3' },
  { title: '不再犹豫 — Beyond', file: 'bu-zai-you-yu-beyond.mp3' },
  { title: '空心 — 光泽', file: 'kong-xin-guang-ze.mp3' },
  { title: '董小姐 — 宋冬野', file: 'dong-xiao-jie-song-dongye.mp3' },
  { title: '依恋 — 蔡淳佳', file: 'yi-lian-cai-chun-jia.mp3' },
  { title: '不想失去你 — 张雨生', file: 'bu-xiang-shi-qu-ni-zhang-yu-sheng.mp3' },
  { title: '再见只是陌生人 — 庄心妍', file: 'zai-jian-zhi-shi-mo-sheng-ren-zhuang-xin-yan.mp3' },
  { title: '生如夏花 — 朴树', file: 'sheng-ru-xia-hua-pu-shu.mp3' },
  { title: 'Monody (feat. Laura Brehm) — TheFatRat', file: 'monody-thefatrat-laura-brehm.mp3' },
  { title: '一万个舍不得 — 庄心妍', file: 'yi-wan-ge-she-bu-de-zhuang-xin-yan.mp3' },
  { title: '但愿人长久 — 王菲', file: 'dan-yuan-ren-chang-jiu-wang-fei.mp3' },
  { title: '很爱很爱你 — 刘若英', file: 'hen-ai-hen-ai-ni-liu-ruo-ying.mp3' },
  { title: '星辰大海 — 黄霄云', file: 'xing-chen-da-hai-huang-xiao-yun.mp3' },
  { title: '橄榄树 — 齐豫', file: 'gan-lan-shu-qi-yu.mp3' },
  { title: '江南 — 林俊杰', file: 'jiang-nan-lin-jun-jie.mp3' },
  { title: '烟火里的尘埃 — 黄霄云', file: 'yan-huo-li-de-chen-ai-huang-xiao-yun.mp3' },
  { title: '白桦林 — 朴树', file: 'bai-hua-lin-pu-shu.mp3' },
  { title: '稻香 — 周杰伦', file: 'dao-xiang-zhou-jie-lun.mp3' },
  { title: '花心 — 周华健', file: 'hua-xin-zhou-hua-jian.mp3' },
];
