/** 只转换显示名称，原名继续供几何识别、存档和物理逻辑使用。 */
const names: Record<string, string> = {
  "Technic Angle Connector #1": "科技系列 角度连接件 #1",
  "Technic Angle Connector #2 (180°)": "科技系列 角度连接件 #2 (180°)",
  "Technic Angle Connector #3 (157.5°)": "科技系列 角度连接件 #3 (157.5°)",
  "Technic Angle Connector #4 (135°)": "科技系列 角度连接件 #4 (135°)",
  "Technic Angle Connector #5 (112.5°)": "科技系列 角度连接件 #5 (112.5°)",
  "Technic Angle Connector #6 (90°)": "科技系列 角度连接件 #6 (90°)",
  "Technic Axle 3L with Middle Pin Hole": "科技系列 十字轴 3L 带中部销孔",
  "Technic Axle and Pin Connector Hub 90°": "科技系列 轴销连接毂 90°",
  "Technic Axle Joiner": "科技系列 十字轴 接头",
  "Technic Axle Joiner 3L": "科技系列 十字轴 接头 3L",
  "Technic Axle Joiner Inline Smooth": "科技系列 十字轴 接头 直通 光滑",
  "Technic Axle with Perpendicular Pin Hole": "科技系列 十字轴 带垂直销孔",
  "Technic Ball Joint 2.25 Diameter Socket": "科技系列 球关节 2.25 直径 插座",
  "Technic Beam 3 x 0.5 with Boss": "科技系列 梁 3 × 0.5 带 凸台",
  "Technic Beam 4 x 0.5 with Boss": "科技系列 梁 4 × 0.5 带 凸台",
  "Technic Bush 1/2 Smooth": "科技系列 轴套 1/2 光滑",
  "Technic Bush with Two Flanges": "科技系列 轴套 带双凸缘",
  "Technic Cable Clip": "科技系列 线缆夹",
  "Technic Clutch Axle Connector": "科技系列 离合器 十字轴 连接件",
  "Technic Clutch with Axle Connector Inner Side":
    "科技系列 离合器 带 十字轴 连接件 内侧",
  "Technic Connector (Axle/Bush) Type 1": "科技系列 连接件 (十字轴/轴套) 类型 1",
  "Technic Connector Block 3 x 3 with 9 Perpendicular Holes":
    "科技系列 连接块 3 × 3 带 9 垂直 孔",
  "Technic Connector Circular with 2 Pin Holes and 3 Axle Holes":
    "科技系列 连接件 圆形 带 2 销孔 及 3 十字轴孔",
  "Technic Connector Toggle Joint Smooth Double with 2 Pins":
    "科技系列 连接件 铰接件 光滑 双联 带 2 连接销",
  "Technic Cross Block 1 x 2": "科技系列 十字连接块 1 × 2",
  "Technic Cross Block 1 x 3 (Axle/Pin/Axle)":
    "科技系列 十字连接块 1 × 3 (十字轴/连接销/十字轴)",
  "Technic Cross Block 1 x 3 (Axle/Pin/Pin)":
    "科技系列 十字连接块 1 × 3 (十字轴/连接销/连接销)",
  "Technic Cross Block 1 x 3 (Pin/Pin/Pin) with 2 Pins":
    "科技系列 十字连接块 1 × 3 (连接销/连接销/连接销) 带 2 连接销",
  "Technic Cross Block 1 x 3 with 4 Pins": "科技系列 十字连接块 1 × 3 带 4 连接销",
  "Technic Cross Block 2 x 2": "科技系列 十字连接块 2 × 2",
  "Technic Cross Block 2 x 2 Bent 90 (Pin/Pin/Pin)":
    "科技系列 十字连接块 2 × 2 弯曲 90 (连接销/连接销/连接销)",
  "Technic Cross Block 2 x 2 Split": "科技系列 十字连接块 2 × 2 分体",
  "Technic Cross Block 2 x 3 (Pin/Pin/Twin Pin)":
    "科技系列 十字连接块 2 × 3 (连接销/连接销/双 连接销)",
  "Technic Cross Block 3 x 2": "科技系列 十字连接块 3 × 2",
  "Technic Cross Block Bent 90°": "科技系列 十字连接块 弯曲 90°",
  "Technic Link 2 x 4 Bent 90": "科技系列 连杆 2 × 4 弯曲 90",
  "Technic Pin 3L Double with Axlehole": "科技系列 连接销 3L 双联 带 十字轴孔",
  "Technic Pin Joiner Round with Slot": "科技系列 连接销 接头 圆形 带 开槽",
  "Technic Steel Ball 18mm": "科技系列 钢球 18mm",
  "Technic Toggle Joint Double": "科技系列 铰接件 双联",
  "Technic Tooth 1 x 3 with Axlehole with Rounded Bottom Cavity":
    "科技系列 齿 1 × 3 带 十字轴孔 底部带圆形凹槽",
  "Technic Transmission Changeover Catch Type 1": "科技系列 换挡拨叉 类型 1",
  "Technic Universal Joint 3L (Complete)": "科技系列 万向节 3L (完整组件)",
  "Technic Universal Joint 3L Centre": "科技系列 万向节 3L 中心件",
  "Technic Universal Joint 3L End": "科技系列 万向节 3L 端件",
  "Technic Wedge Belt Wheel": "科技系列 皮带轮",
  "Technic Wedge Belt Wheel Tyre": "科技系列 皮带轮 轮胎",
  "Tyre 6/30 x 11": "轮胎 6/30 × 11",
  "Tyre 20/64 x 37": "轮胎 20/64 × 37",
  "Wheel Rim 8 x 11.2 with Centre Groove": "轮毂 8 × 11.2 带中心槽",
  "Wheel Rim 8 x 18 with Deep Centre Groove and Axle Hole":
    "轮毂 8 × 18 带深中心槽 及 十字轴孔",
  "Wheel Rim 8 x 18 with Deep Centre Groove, Deep Spokes and Peghole":
    "轮毂 8 × 18 带深中心槽, 深轮辐 及 销孔",
  "Wheel Rim 14 x 18 Axlehole": "轮毂 14 × 18 十字轴孔",
  "Wheel Rim 14 x 18 Holes": "轮毂 14 × 18 孔",
  "Wheel Rim 14 x 30 with 6 Spokes and No Pegholes": "轮毂 14 × 30 带 6 轮辐 及 无销孔",
  "Wheel Rim 18 x 37 with 6 Pegholes and Short Axle Bush":
    "轮毂 18 × 37 带 6 销孔 及 短轴套",
  "Wheel Rim 20 x 30 Dual Spokes": "轮毂 20 × 30 双轮辐",
  "Wheel Rim 26 x 43 with 6 Spokes and 6 Pegholes": "轮毂 26 × 43 带 6 轮辐 及 6 销孔",
  "Wheel Rim 34 x 56 with 6 Spokes and 6 Pegholes": "轮毂 34 × 56 带 6 轮辐 及 6 销孔",
  "Rubber Belt Round 15 / 1.6": "圆形橡皮筋 15 / 1.6",
  "Rubber Belt Round 26 / 1.6": "圆形橡皮筋 26 / 1.6",
  "Rubber Belt Round 33 / 1.6": "圆形橡皮筋 33 / 1.6",
  "Technic Axle Joiner Double Flexible": "科技系列 十字轴 接头 双联 柔性",
  "Technic Pneumatic Cylinder 1 x 11": "科技系列 气缸 1 × 11",
  "Technic Pneumatic Cylinder 2 x 11": "科技系列 气缸 2 × 11",
  "Technic Pneumatic Hose Connector with Bush": "科技系列 气动软管连接件 带 轴套",
  "Technic Pneumatic T-Piece Type 2": "科技系列 气动 T 形接头 类型 2",
  "Technic Axle Pin": "科技系列 十字轴销",
  "Technic Axle Pin Long with Friction, 2L Axle":
    "科技系列 十字轴销 长型 带摩擦, 2L 十字轴",
  "Technic Axle Pin Long with Friction, 2L Pin":
    "科技系列 十字轴销 长型 带摩擦, 2L 连接销",
  "Technic Axle Pin Long without Friction": "科技系列 十字轴销 长型 无摩擦",
  "Technic Axle Pin with Friction": "科技系列 十字轴销 带摩擦",
  "Technic Axle Towball": "科技系列 十字轴 球头",
  "Technic Pin 1/2": "科技系列 连接销 1/2",
  "Technic Pin 1/2 with Friction": "科技系列 连接销 1/2 带摩擦",
  "Technic Pin 3/4": "科技系列 连接销 3/4",
  "Technic Pin Long with End Stop": "科技系列 连接销 长型 带端部限位",
  "Technic Pin Long with Friction and Slot": "科技系列 连接销 长型 带摩擦与开槽",
  "Technic Pin Long with Pin Hole": "科技系列 连接销 长型 带 销孔",
  "Technic Pin Long with Stop Bush": "科技系列 连接销 长型 带限位轴套",
  "Technic Pin Long without Friction": "科技系列 连接销 长型 无摩擦",
  "Technic Pin Towball with Friction": "科技系列 连接销 球头 带摩擦",
  "Technic Pin with Friction and Perpendicular Hole": "科技系列 连接销 带摩擦 及 垂直 孔",
  "Technic Pin with Friction and Slots": "科技系列 连接销 带摩擦与开槽",
  "Technic Pin without Friction": "科技系列 连接销 无摩擦",
  "Technic Axle 2 Notched": "科技系列 十字轴 2 带槽",
  "Technic Axle 3": "科技系列 十字轴 3",
  "Technic Axle 3 with Stop": "科技系列 十字轴 3 带限位",
  "Technic Axle 3 with Stud": "科技系列 十字轴 3 带凸点",
  "Technic Axle 4": "科技系列 十字轴 4",
  "Technic Axle 4 with Middle Cylindrical Stop": "科技系列 十字轴 4 带中部圆柱限位",
  "Technic Axle 4 with Stop": "科技系列 十字轴 4 带限位",
  "Technic Axle 5": "科技系列 十字轴 5",
  "Technic Axle 5 with Stop": "科技系列 十字轴 5 带限位",
  "Technic Axle 5.5 with Stop": "科技系列 十字轴 5.5 带限位",
  "Technic Axle 6": "科技系列 十字轴 6",
  "Technic Axle 7": "科技系列 十字轴 7",
  "Technic Axle 8": "科技系列 十字轴 8",
  "Technic Axle 8 with Stop": "科技系列 十字轴 8 带限位",
  "Technic Axle 9": "科技系列 十字轴 9",
  "Technic Axle 10": "科技系列 十字轴 10",
  "Technic Axle 11": "科技系列 十字轴 11",
  "Technic Axle 12": "科技系列 十字轴 12",
  "Technic Axle Connector 1.5": "科技系列 十字轴 连接件 1.5",
  "Technic Changeover Catch Fork": "科技系列 换挡拨叉",
  "Technic Changeover Cylinder with Groove": "科技系列 换挡圆柱 带 槽",
  "Technic Changeover Rotary Catch": "科技系列 旋转换挡拨叉",
  "Technic Differential with Gear 16 Tooth and 24 Tooth":
    "科技系列 差速器 带 齿轮 16 齿 及 24 齿",
  "Technic Differential with One Gear 28 Tooth Bevel":
    "科技系列 差速器 带 一个 齿轮 28 齿 锥齿",
  "Technic Gear 4 Knob": "科技系列 齿轮 4 凸齿",
  "Technic Gear 8 Tooth Reinforced": "科技系列 齿轮 8 齿 加强型",
  "Technic Gear 12 Tooth Bevel": "科技系列 齿轮 12 齿 锥齿",
  "Technic Gear 12 Tooth Double Bevel": "科技系列 齿轮 12 齿 双锥面",
  "Technic Gear 16 Tooth Reinforced": "科技系列 齿轮 16 齿 加强型",
  "Technic Gear 16 Tooth with Clutch (1 stud)": "科技系列 齿轮 16 齿 带离合 (1 格)",
  "Technic Gear 16 Tooth with Clutch on Both Sides": "科技系列 齿轮 16 齿 双侧带离合",
  "Technic Gear 20 Tooth Bevel": "科技系列 齿轮 20 齿 锥齿",
  "Technic Gear 20 Tooth Bevel with Peghole": "科技系列 齿轮 20 齿 锥齿 带 销孔",
  "Technic Gear 20 Tooth Double Bevel": "科技系列 齿轮 20 齿 双锥面",
  "Technic Gear 20 Tooth Double Bevel with Clutch on Both Sides":
    "科技系列 齿轮 20 齿 双锥面 双侧带离合",
  "Technic Gear 24 Tooth": "科技系列 齿轮 24 齿",
  "Technic Gear 28 Tooth Double Bevel": "科技系列 齿轮 28 齿 双锥面",
  "Technic Gear 36 Tooth Double Bevel": "科技系列 齿轮 36 齿 双锥面",
  "Technic Gear 40 Tooth": "科技系列 齿轮 40 齿",
  "Technic Gear Rack 1 x 4": "科技系列 齿条 1 × 4",
  "Technic Gear Rack 1 x 7": "科技系列 齿条 1 × 7",
  "Technic Gear Rack 1 x 8 with Holes": "科技系列 齿条 1 × 8 带 孔",
  "Technic Gear Rack 1 x 10 with Holes": "科技系列 齿条 1 × 10 带 孔",
  "Technic Gear Rack 1 x 13": "科技系列 齿条 1 × 13",
  "Technic Gear Rack 1 x 14": "科技系列 齿条 1 × 14",
  "Technic Gear Rack 1 x 14 Beam": "科技系列 齿条 1 × 14 梁",
  "Technic Gear Rack 1 x 14 Housing": "科技系列 齿条 1 × 14 外壳",
  "Technic Gear Ring Quarter 15 Tooth": "科技系列 四分之一齿圈 15 齿",
  "Technic Gear Ring Quarter 35 Tooth": "科技系列 四分之一齿圈 35 齿",
  "Technic Gear Shifter with Axle Hole 30 degrees Offset":
    "科技系列 换挡件 带 十字轴孔 30 度 偏置",
  "Technic Gear Shifter with Axle Hole 60 degrees Offset":
    "科技系列 换挡件 带 十字轴孔 60 度 偏置",
  "Technic Transmission Driving Ring": "科技系列 变速传动环",
  "Technic Transmission Driving Ring 3L": "科技系列 变速传动环 3L",
  "Technic Transmission Driving Ring Extension": "科技系列 变速传动环延长件",
  "Technic Turntable 28 Tooth (Complete)": "科技系列 转盘 28 齿 (完整组件)",
  "Technic Turntable 28 Tooth Top": "科技系列 转盘 28 齿 顶部",
  "Technic Turntable 60 Tooth (Complete)": "科技系列 转盘 60 齿 (完整组件)",
  "Technic Turntable 60 Tooth Bottom": "科技系列 转盘 60 齿 底部",
  "Technic Worm Gear 1L": "科技系列 蜗杆 1L",
  "Technic Worm Gear 2L with Axle Hole Two-toothed Sliding":
    "科技系列 蜗杆 2L 带 十字轴孔 双齿 滑动",
  "Technic Beam 1": "科技系列 梁 1",
  "Technic Beam 1 x 2 (legacy 44)": "科技系列 梁 1 × 2 (旧编号 44)",
  "Technic Beam 2": "科技系列 梁 2",
  "Technic Beam 2 Liftarm": "科技系列 梁 2 升降臂",
  "Technic Beam 3": "科技系列 梁 3",
  "Technic Beam 5": "科技系列 梁 5",
  "Technic Beam 7": "科技系列 梁 7",
  "Technic Beam 9": "科技系列 梁 9",
  "Technic Beam 11": "科技系列 梁 11",
  "Technic Beam 13": "科技系列 梁 13",
  "Technic Beam 15": "科技系列 梁 15",
  "Technic Beam 2 x 0.5 Liftarm": "科技系列 梁 2 × 0.5 升降臂",
  "Technic Beam 3 x 0.5 Liftarm": "科技系列 梁 3 × 0.5 升降臂",
  "Technic Beam 3 x 3 x 0.5 Bent 90°": "科技系列 梁 3 × 3 × 0.5 弯曲 90°",
  "Technic Beam 3 x 5 x 0.5 Liftarm Bent 90 Quarter Ellipse":
    "科技系列 梁 3 × 5 × 0.5 升降臂 弯曲 90 四分之一椭圆",
  "Technic Beam 4 x 0.5 Liftarm": "科技系列 梁 4 × 0.5 升降臂",
  "Technic Beam 5 x 0.5": "科技系列 梁 5 × 0.5",
  "Technic Beam 5 x 0.5 with Axle Holes": "科技系列 梁 5 × 0.5 带 十字轴孔",
  "Technic Beam 5 x 3 x 0.5 Triangle": "科技系列 梁 5 × 3 × 0.5 三角形",
  "Technic Beam 6 x 0.5": "科技系列 梁 6 × 0.5",
  "Technic Beam 7 x 0.5": "科技系列 梁 7 × 0.5",
  "Technic Beam 7 Alternating Holes": "科技系列 梁 7 交替孔",
  "Technic Beam 7 x 5 Open Center": "科技系列 梁 7 × 5 中空",
  "Technic Beam 11 Alternating Holes": "科技系列 梁 11 交替孔",
  "Technic Beam 11 x 5 Open Center": "科技系列 梁 11 × 5 中空",
  "Technic Beam 11 x 7 Open Center": "科技系列 梁 11 × 7 中空",
  "Technic Beam 15 Alternating Holes": "科技系列 梁 15 交替孔",
  "Technic Beam 15 x 11 Open Center": "科技系列 梁 15 × 11 中空",
  "Technic Beam 19 x 3 with Three Open Areas 5 x 1":
    "科技系列 梁 19 × 3 带三个开口 5 × 1",
  "Technic Beam 2 x 3 C-shaped": "科技系列 梁 2 × 3 C 形",
  "Technic Beam 2 x 3 Liftarm Bent 90° Quarter Ellipse":
    "科技系列 梁 2 × 3 升降臂 弯曲 90° 四分之一椭圆",
  "Technic Beam 2 x 4 Bent 90°": "科技系列 梁 2 × 4 弯曲 90°",
  "Technic Beam 2 x 5 Liftarm Bent 90 Quarter Ellipse":
    "科技系列 梁 2 × 5 升降臂 弯曲 90 四分之一椭圆",
  "Technic Beam 3 x 3 T-shaped": "科技系列 梁 3 × 3 T 形",
  "Technic Beam 3 x 5 Bent 90": "科技系列 梁 3 × 5 弯曲 90",
  "Technic Beam 3 x 5 Bent 90°": "科技系列 梁 3 × 5 弯曲 90°",
  "Technic Beam 3 x 7 Bent 53.13°": "科技系列 梁 3 × 7 弯曲 53.13°",
  "Technic Beam 4 x 4 Liftarm Bent 53.13": "科技系列 梁 4 × 4 升降臂 弯曲 53.13",
  "Technic Beam 4 x 6 Liftarm Bent 53.13": "科技系列 梁 4 × 6 升降臂 弯曲 53.13",
  "Technic Beam 5 x 3 H-shaped": "科技系列 梁 5 × 3 H 形",
  "Technic Beam 5 x 7 Bent Quarter Ellipse": "科技系列 梁 5 × 7 弯曲 四分之一椭圆",
  "Technic Beam 19 x 11 Baseplate": "科技系列 梁 19 × 11 底板",
  "Technic Liftarm Bent 45 Double": "科技系列 升降臂 弯曲 45 双联",
  "Technic Liftarm Bent 90 Quarter Circle": "科技系列 升降臂 弯曲 90 四分之一圆",
  "Technic Panel 3 x 7": "科技系列 面板 3 × 7",
  "Technic Panel 3 x 11": "科技系列 面板 3 × 11",
  "Technic Panel 5 x 11": "科技系列 面板 5 × 11",
  "Technic Pin Connector 3 x 3 Bent 90°": "科技系列 连接销 连接件 3 × 3 弯曲 90°",
};
export const displayPartName = (name: string, language = "zh-CN") =>
  language === "zh-CN" ? (names[name] ?? name) : name;
